# Generated by Django 4.2.28 on 2026-02-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lottery",
            "0004_alter_badge_id_alter_badgeaward_id_alter_entry_id_and_more"
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="winner_rank",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
