# Generated by Django 4.2.28 on 2026-02-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_alter_pet_age'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_pet_per_owner_name'),
        ),
    ]
