# Generated by Django 4.2.28 on 2026-02-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_badgeaward_pet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='badgeaward',
            name='unique_badge_award_per_round',
        ),
        migrations.AlterUniqueTogether(
            name='badgeaward',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='badgeaward',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='lottery.pet'),
        ),
        migrations.AddConstraint(
            model_name='badgeaward',
            constraint=models.UniqueConstraint(fields=('user', 'pet', 'badge', 'round'), name='unique_badge_award_per_pet_round'),
        ),
    ]
