# Generated by Django 4.2.28 on 2026-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0011_notification_pet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_notification_per_round',
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'pet', 'round'), name='unique_notification_per_pet_round'),
        ),
    ]
